name: rtngs CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy app to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "entering rtngs directory..."
            cd rtngs
            echo "sync codes..."
            git pull
            echo "reload api..."
            pm2 reload api-rtngs
            pm2 save
            pm2 startup
            echo "build frontend..."
            rm -rf /frontend/dist
            yarn --cwd /frontend build
            echo "update static production..."
            sudo rm -rf /var/www/rtngs
            sudo cp -R /frontend/dist /var/www/rtngs
            echo "Deployment success."
