name: rtngs CD
on:
  push:
    branches: [main]
jobs:
  test:
    name: Automated Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Use node.js ${ matrix.node-version }} - ${{ matrix.architecture }}
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Unit test
        run: yarn test
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ./rtngs.sh
